<?php

namespace EventsBundle\Repository;

/**
 * FeedRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FeedRepository extends \Doctrine\ORM\EntityRepository
{

    function findFeedbyEvent($id){
        $query=$this->getEntityManager()
            ->createQuery("select c from EventsBundle:Feed c WHERE c.idEvent LIKE :id")
            ->setParameter('id','%'.$id.'%');
        return $query->getResult();
    }

    function AllFeeds(){
        $query=$this->getEntityManager()
            ->createQuery("select c from EventsBundle:Feed c WHERE c.description != '' ");
        return $query->getResult();
    }


}
