<?php

namespace EventsBundle\Repository;

/**
 * ParticipeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ParticipeRepository extends \Doctrine\ORM\EntityRepository
{

    function NbrParticipantParEvent($id){
        $query=$this->getEntityManager()
            ->createQuery("select COUNT(c.id) from EventsBundle:Participe c WHERE c.idEvent LIKE :id")
            ->setParameter('id','%'.$id.'%');
        return $query->getSingleScalarResult();
    }

    function IsParticiped($idEvenement,$IdUser){
        $query=$this->getEntityManager()
            ->createQuery("select COUNT(c.id) from EventsBundle:Participe c WHERE c.idEvent LIKE '".$idEvenement."' AND c.idUser LIKE '".$IdUser."'") ;
        return $query->getSingleScalarResult();
    }

}
